version: '3.8'

services:
  flexpro-api:
    build:
      context: . 
      dockerfile: Dockerfile 
    ports:
      - "5000:8080"
      - "5001:8081"
    environment: 
      - ASPNETCORE_ENVIRONMENT=Development  
      - ASPNETCORE_URLS=https://+:8081;http://+:8080
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Xj7hpmtmma@
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx 
    volumes:
        - ~/.aspnet/https:/https:ro
    restart: always   
    networks:
      - flexpro-network

networks:
  flexpro-network:
    external: true
