version: '3.8'

services:
  flexpro-api:
    build:
      context: . 
      dockerfile: Dockerfile 
    ports:
      - "5000:8080"
    environment: 
      - ASPNETCORE_ENVIRONMENT=Development  
    restart: always   
    networks:
      - flexpro-network

networks:
  flexpro-network:
    external: true