version: '3.8'

services:
  flexpro-api:
    build:
      context: . 
      dockerfile: Dockerfile 
    ports:
    - "5000:5000"  
    environment:
      ASPNETCORE_ENVIRONMENT: Production  
    restart: always  
    networks:
      - flexpro-network

networks:
  flexpro-network:
    driver: bridge
