//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlexPro.Api.Properties {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("FlexPro.Infrastructure.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static byte[] Capa_Consultoria {
            get {
                object obj = ResourceManager.GetObject("Capa-Consultoria", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Conexão {
            get {
                object obj = ResourceManager.GetObject("Conexão", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] consultoria_imagem {
            get {
                object obj = ResourceManager.GetObject("consultoria-imagem", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Logo_Proauto {
            get {
                object obj = ResourceManager.GetObject("Logo-Proauto", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Posto01 {
            get {
                object obj = ResourceManager.GetObject("Posto01", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Posto02 {
            get {
                object obj = ResourceManager.GetObject("Posto02", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Posto03 {
            get {
                object obj = ResourceManager.GetObject("Posto03", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
